["sublib",
"langs",
"isbn",
"title",
"tr_title",
"subtitle",
"tr_subtitle",
"parallel_title",
"tr_parallel_title",
"parallel_subtitle",
"tr_parallel_subtitle",
"country_name",
"place",
"publisher",
"pub_year",
"copyright",
"pagination",
"size",
"illustrations",
"series_title",
"series_enum",
"volume",
"notes",
"sales_code",
"sale_dates",
"hol_notes",
"donation",
"barcode",]


["Library",
"language of resource",
"ISBN",
"Title",
"Title transliteration",
"Subtitle",
"Subtitle transliteration",
"Parallel title (dual language only)",
"Parallel title transliteration",
"Parallel subtitle (dual language only)",
"Parallel subtitle transliteration",
"Country of publication",
"(State,) City of publication",
"Publisher's name",
"Year of publication",
"Year of copyright",
"Number of pages",
"Size (height)",
"Illustrations",
"Series title",
"Series enumeration",
"Volume",
"Note",
"Sale code",
"Date of auction",
"HOL notes",
"Donor note",
"Barcode",]